# Default agents to run when --agents is not specified
# Uses case-insensitive substring matching
default_agents = ["copilot", "claude", "aider"]

# --- Global MCP Server Configuration ---
[mcp]
# Enable/disable MCP propagation globally (default: true)
enabled = false
# Global merge strategy: 'merge' or 'overwrite' (default: 'merge')
merge_strategy = "merge"

# --- MCP Server Definitions ---
[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/project"]

[mcp_servers.git]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-git", "--repository", "."]

[mcp_servers.remote_api]
url = "https://api.example.com"

[mcp_servers.remote_api.headers]
Authorization = "Bearer your-token"

# --- Global .gitignore Configuration ---
[gitignore]
# Enable/disable automatic .gitignore updates (default: true)
enabled = true

# --- Agent-Specific Configurations ---
[agents.copilot]
enabled = true
output_path = ".ruler/.github/copilot-instructions.md"

[agents.claude]
enabled = false
output_path = "CLAUDE.md"

[agents.aider]
enabled = false
output_path_instructions = "AGENTS.md"
output_path_config = ".aider.conf.yml"

# OpenAI Codex CLI agent and MCP config
[agents.codex]
enabled = false
output_path = "AGENTS.md"
output_path_config = ".codex/config.toml"

# Agent-specific MCP configuration for Codex CLI
[agents.codex.mcp]
enabled = false
merge_strategy = "merge"

[agents.firebase]
enabled = false
output_path = ".ruler/.idx/airules.md"

[agents.gemini-cli]
enabled = true

[agents.jules]
enabled = false

[agents.junie]
enabled = false
output_path = ".ruler/.junie/guidelines.md"

# Agent-specific MCP configuration
[agents.cursor.mcp]
enabled = false
merge_strategy = "merge"

# Disable specific agents
[agents.windsurf]
enabled = false

[agents.kilocode]
enabled = false
output_path = ".ruler/.kilocode/rules/ruler_kilocode_instructions.md"

[agents.warp]
enabled = false
output_path = "WARP.md"

# --- Rules Configuration ---
# List of rule files to load for Ruler
[rules]
files = [
  ".amazonq/rules/ruler_q_rules.md",
  ".augment/rules/ruler_augment_instructions.md",
  ".cursor/rules/ruler_cursor_instructions.mdc",
  ".kilocode/rules/ruler_kilocode_instructions.md",
  ".kiro/steering/ruler_kiro_instructions.md",
  ".trae/rules/project_rules.md",
  ".windsurf/rules/ruler_windsurf_instructions.md",
  "AGENTS.md",
  "CLAUDE.md",
  ".idx/airules.md",
  ".junie/guidelines.md",
  "WARP.md"
]